import sqlite3
import pandas as pd
import os

class AdaptiveEngine:
    def __init__(self, db_path="~/.rdq/review_index.db"):
        # Expand user path if necessary, though in sandbox we might use local paths for testing
        self.db_path = os.path.expanduser(db_path)

    def load_student_profile(self) -> pd.DataFrame:
        """
        Reads the review_index.db generated by RDQ and returns a DataFrame
        representing the student's current weaknesses.
        """
        if not os.path.exists(self.db_path):
            print(f"[AdaptiveEngine] Warning: RDQ database not found at {self.db_path}. Using baseline.")
            return pd.DataFrame()

        try:
            conn = sqlite3.connect(self.db_path)
            # Assuming a table named 'student_weakness_log' or similar based on the agreement
            # Let's try to query an 'items' or 'review_log' table based on standard conventions
            # The agreement specifies item_id, status, loss_reason.

            # Since we don't know the exact table name from RDQ, let's assume 'review_log' for now,
            # or try to find a table containing these columns.

            # Query table names
            cursor = conn.cursor()
            cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
            tables = cursor.fetchall()

            target_table = None
            for table in tables:
                table_name = table[0]
                cursor.execute(f"PRAGMA table_info({table_name})")
                cols = [info[1] for info in cursor.fetchall()]
                if 'item_id' in cols and 'status' in cols:
                    target_table = table_name
                    break

            if not target_table:
                print("[AdaptiveEngine] Could not find a table with required schema (item_id, status) in DB.")
                return pd.DataFrame()

            query = f"SELECT item_id, status, loss_reason FROM {target_table}"
            df = pd.read_sql_query(query, conn)
            conn.close()

            return df
        except Exception as e:
            print(f"[AdaptiveEngine] Error reading DB: {e}")
            return pd.DataFrame()

    def get_priority_modifiers(self) -> dict:
        """
        Returns a dictionary mapping X軸代碼 to a multiplier based on student status.
        uncertain/clarified gets a > 1 multiplier (e.g., 1.5x)
        confirmed gets a < 1 multiplier (e.g., 0.5x)
        """
        df = self.load_student_profile()
        if df.empty:
            return {}

        modifiers = {}
        # Group by item_id and get the latest/most severe status.
        # Assuming last entry per item_id is the most relevant.
        # Simple implementation:

        for _, row in df.iterrows():
            code = row.get('item_id')
            status = row.get('status')

            if not code or pd.isna(code):
                continue

            if status in ['uncertain', 'clarified']:
                modifiers[code] = 1.5  # Boost priority by 50%
            elif status == 'confirmed':
                modifiers[code] = 0.5  # Reduce priority by 50%

        return modifiers

    def get_latest_weakness_summary(self) -> dict:
        """Returns the most recent uncertain/clarified topic and its loss reason for the greeting."""
        df = self.load_student_profile()
        if df.empty:
            return {}

        weak_df = df[df['status'].isin(['uncertain', 'clarified'])]
        if weak_df.empty:
            return {}

        # Assuming the last row is the most recent
        latest = weak_df.iloc[-1]
        return {
            'topic': latest.get('item_id', '未指定主題'),
            'reason': latest.get('loss_reason', '未分析出原因')
        }
